modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = "A valid URL to your issue tracker where people can open bug tickets"
license = "MIT License"

[[mods]]
modId = "coxinhacobbletweaks"
version = "${version}"
displayName = "Coxinha Cobble Tweaks"
authors = "fullsets"
description = '''
Adicionando coisas aleatórias
'''
#logoFile = ""

[[dependencies.coxinhacobbletweaks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.coxinhacobbletweaks]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.66,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.coxinhacobbletweaks]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.6.0,)"
ordering = "AFTER"
side = "BOTH"
